- README.md
The readme for the 'services' incorrectly points to the 'obj' .
> doc(*): fix the incorrect file link in the readme.

- jetstream/src/jsapi_types.ts
- jetstream/src/jsmconsumer_api.ts
- jetstream/src/types.ts
- services/src/service.ts
- services/src/types.ts
ported over fix from https://github.com/nats-io/nats.deno/pull/727/files
doc(jetstream,services): modified description of types that are in nanoseconds as jsdoc removes the type alias.
fix(services): `processing_time` was reported in millis instead of nanos
> ported fix 727 from nats.deno

- TODO.md
- kv/src/kv.ts
- kv/tests/kv_test.ts
- migration.md
- obj/src/objectstore.ts
- obj/src/types.ts
- obj/tests/objectstore_test.ts
Update the `watch` methods in ObjectStore and KeyValue classes to use `ObjectWatchInfo` and `KvWatchEntry` types. Removed use of null signals, replaced with property `isUpdate` to indicate new entries. Added relevant tests to validate the changes.
> Refactor object and key-value store watch methods

- core/src/core.ts
- core/src/internal_mod.ts
- core/src/mod.ts
- core/src/protocol.ts
- services/src/service.ts
Renamed internal `Sub` interface to `Subscription` removing the type alias `Subscription`. Removed the unnecessary `Base` and `Sub` interface, simplifying the codebase and reducing redundancy. The `Sub` interface was required for legacy JetStream subscriptions.
> refactor(core): Consolidate Subscription type and remove Base interface

- jetstream/src/jsm.ts
This is a cherry pick from https://github.com/nats-io/nats.deno/pull/729
Fix #96
Thanks @SalvaChiLlo
> fix(jetstream): direct get api now uses the configured timeout in the context

- jetstream/src/internal_mod.ts
- jetstream/src/mod.ts
- kv/src/kv.ts
- kv/src/types.ts
- obj/src/internal_mod.ts
- obj/src/mod.ts
- obj/src/types.ts
- fix(jetstream): exported ApiError
- change(kv): removed deprecated KV apis (`KvRemove` - `remove(k)=>Promise<void>`, `close()=>Promise<void>`) and - - options (`maxBucketSize`, `placementCluster`, `bucket_location`)
- fix(obj): exported ObjectWatchInfo type
- change(obj): removed deprecated `ObjectStoreInfo` - use `ObjectStoreStatus`
> removed deprecations and exported some missing symbols

- services/src/service.ts
- services/src/types.ts
- services/tests/service_test.ts
breaking (services): the queue property now, if set to an empty string, means that the service/endpoint/group will not be in a queue. Clients that specifically assign queue names should experience no changes. Clients that didn't specify a value for the property (so the property was undefined) should also not experience a change and should see their service/endpoint/group use the `q` group. If explicitly set to an empty string ``, the service will NOT be part of a queue.
breaking (services): The metadata configuration specified when creating the service is now stored read-only. Any edit on the internal copy will result in a `TypeError` as the metadata object is frozen.
> FEAT: services api queue option empty string means no queue, metadata is read-only

- jetstream/deno.json
- jetstream/package.json
- jetstream/src/jsm.ts
- jetstream/src/jsmstream_api.ts
- jetstream/src/types.ts
- jetstream/tests/jetstream_test.ts
- jetstream/tests/jsm_test.ts
- jetstream/tests/streams_test.ts
- kv/deno.json
- kv/import_map.json
- kv/package.json
- kv/src/kv.ts
- migration.md
- obj/deno.json
- obj/import_map.json
- obj/package.json
- obj/src/objectstore.ts
Refactor JetStream's getMessage() method to return null instead of throwing an error when a message is not found. This change simplifies error handling in client code and aligns with other API behaviors.
Fix #122
> change(jetstream): Stream.getMessage() to return null for non-existent messages

- jetstream/src/jsmstream_api.ts
- jetstream/tests/consumers_ordered_test.ts
> fix(jetstream): ordered consumer created with DeliverPolicy.All would fail since the default was specifying a sequence

- core/src/nats.ts
- core/src/protocol.ts
- core/tests/events_test.ts
- jetstream/tests/fetch_test.ts
- jetstream/tests/jsm_direct_test.ts
> fixed a resource leak that prevented status iterators from cleaning properly

- core/src/core.ts
- core/src/protocol.ts
- core/tests/auth_test.ts
- migration.md
feat(core): subscriptions `closed` promise can now resolve to void or Error - if error the subscription was closed due to an error. Note that it doesn't reject, but rather resolves to the Error.
> subscription closed promise can now provide the reason for the close

- jetstream/src/consumer.ts
- jetstream/tests/consume_test.ts
- jetstream/tests/consumers_ordered_test.ts
- jetstream/tests/consumers_test.ts
- jetstream/tests/fetch_test.ts
- jetstream/tests/jetstream_pullconsumer_test.ts
- jetstream/tests/jetstream_test.ts
- jetstream/tests/next_test.ts
- migration.md
- test_helpers/mod.ts
fix(jetstream) fetch/next() now rely on missing heartbeat detection to fail requests that were not properly "finished" by the server. This has the benefit that messages arriving "late" are now likely to complete successfully since the client won't be proactively ending the request.
change(jetstream) non-ordered fetch/next will now throw/reject if heartbeats are missed - previously you could find out if you had statuses enabled on the fetch. On next() it was silently ignored and the client received a null message.
tests(jetstream): removed flapper tests that attempted yield ConsumerNotFound/StreamNotFound when a resource as removed prior to a consume/fetch/next.
tests(jestream): fixed cross-account configurations to have a response_type of "stream"
There's also a small implication for the …
> fetch()/next() rely on missed heartbeats to detect abnormally ending next requests

- jetstream/deno.json
- jetstream/package.json
- jetstream/src/consumer.ts
- jetstream/src/internal_mod.ts
- jetstream/src/jserrors.ts
- jetstream/src/mod.ts
- jetstream/src/pushconsumer.ts
- jetstream/src/types.ts
- jetstream/tests/consume_test.ts
- jetstream/tests/consumers_ordered_test.ts
- jetstream/tests/consumers_test.ts
- jetstream/tests/jetstream409_test.ts
- jetstream/tests/jetstream_pushconsumer_test.ts
- kv/deno.json
- kv/import_map.json
- kv/package.json
- migration.md
- obj/deno.json
- obj/import_map.json
- obj/package.json
- transport-node/package.json
change(jetstream): `ConsumerStatus` and `ConsumerDebugStatus` are now… replaced by `ConsumerNotification` which is an alias for specific types for the the different notifications. All discriminated by their `type` field. This simplifies down-stream consumption and provides a richer API for accessing the data in the notification.
> ConsumerStatus changed to simple type `ConsumerNotification`

- README.md
1. each lib has it's own release badge now
2. @aricart to fix the coverage badge eventually
[ci skip]
> Drop wrong badges

- migration.md
- services/deno.json
- services/examples/01_services.ts
- services/examples/02_multiple_endpoints.ts
- services/examples/03_bigdata.ts
- services/package.json
- services/src/internal_mod.ts
- services/src/mod.ts
- services/tests/service-check.ts
- services/tests/service_test.ts
fix(obj): changed test references to jsr bundles pointing wrong transport bundle
> change(obj): changed `Svc` to `Svcm` to align with `Kvm`, `Objm`, etc

- README.md
The README now displays badges for the example CI workflow and test coverage, providing more visibility into the project's status. This helps users quickly assess build health and code coverage.
[ci skip]
> Add badges for CI workflow and test coverage to README

- jetstream/src/jsapi_types.ts
- jetstream/src/jsm_direct.ts
- jetstream/src/jsmstream_api.ts
- jetstream/src/types.ts
- jetstream/tests/direct_consumer_test.ts
- jetstream/tests/jsm_direct_test.ts
internal implementation for a direct consumer.
> internal(jetstream): direct consumer

- kv/src/types.ts
- kv/tests/kv_test.ts
- migration.md
The `backingStore` field in `KvOptions` and `KvStatus` was removed. References in the tests were updated to use `storage` instead. The migration guide was updated to reflect this change and provide guidance for users.
> Remove deprecated `backingStore` from KV types and tests

- jetstream/src/jsapi_types.ts
- jetstream/src/jsmsg.ts
- jetstream/tests/jetstream_test.ts
- jetstream/tests/jsmsg_test.ts
- jetstream/tests/next_test.ts
- migration.md
Renamed `redeliveryCount` to `deliveryCount` to better reflect its purpose, as it tracks all delivery attempts, not just redeliveries. Updated related logic, documentation, and test cases to align with the new naming. Added a migration note for developers regarding this change.
Fixes #186
> Update redeliveryCount to deliveryCount across codebase

- jetstream/src/consumer.ts
- jetstream/tests/consume_test.ts
- jetstream/tests/consumers_push_test.ts
- jetstream/tests/fetch_test.ts
- jetstream/tests/next_test.ts
Ensure consumers stop upon connection closure by adding proper checks and cleanup mechanisms. Added corresponding tests to validate behavior across fetch, consume, and next methods.
> Handle connection closure gracefully in consumers.

- jetstream/src/jsmstream_api.ts
- jetstream/src/types.ts
- jetstream/tests/consumers_test.ts
Introduce a `getConsumerFromInfo` method to retrieve a pull consumer without fetching ConsumerInfo. This ensures efficient consumer handling while avoiding unnecessary API calls. Included corresponding tests to validate functionality.
> feat(JS): `getConsumerFromInfo` method for pull consumer retrieval

- core/deno.json
- core/package.json
- core/src/version.ts
- docs/package.json
- jetstream/deno.json
- jetstream/import_map.json
- jetstream/package.json
- kv/deno.json
- kv/import_map.json
- kv/package.json
- obj/deno.json
- obj/import_map.json
- obj/package.json
- services/deno.json
- services/import_map.json
- services/package.json
- transport-deno/deno.json
- transport-deno/src/version.ts
- transport-node/package.json
- transport-node/src/version.ts
Updated package versions across multiple modules, including `nats-core`, `jetstream`, `kv`, `nkeys`, and `nuid`. Removed doc scripts and configuration from packages while centralizing documentation generation in a new `docs/package.json` file. These changes aim to simplify dependency management and streamline the documentation process.
> Bump dependencies and remove typedoc configurations.

- jetstream/src/types.ts
This PR changes the `callback` type on `ConsumeOptions` to allow linters to explicitly call out the fact that the `callback` parameter **will not be `await`'d and is therefore an error if an `async` method is passed in**.
> Add 'Promise<never>' to ConsumerCallbackFn

- transport-node/src/node_transport.ts
Removed unnecessary variable assignment for `debug` and directly accessed `this.options.debug` instead, this enables changing the debug option on the fly and have the client print/stop as necessary.
> fix(transport-node): reference this.options.debug for dynamic show-hide client protocol

- kv/src/kv.ts
Introduce a heartbeat case to handle key iteration status updates. This ensures proper key fetching and stops the iteration appropriately upon receiving a heartbeat.
> Add heartbeat handling to key iteration

- deno.json
- test_helpers/certs.ts
- test_helpers/cluster.ts
- test_helpers/connect.ts
- test_helpers/deno.json
- test_helpers/launcher.ts
- test_helpers/mod.ts
- test_helpers/test_server.ts
- test_helpers/util.ts
- transport-deno/examples/bench.js
Replaced file path imports with package-based imports for improved clarity and maintainability. Added a new `test_helpers/deno.json` configuration and updated the `test_helpers` module structure to streamline the usage of helper utilities. Also updated the transport package reference in the examples for consistency.
> Update imports to use package names and enhance test helpers

- core/deno.json
- core/package.json
- core/src/version.ts
- core/src/ws_transport.ts
- jetstream/deno.json
- jetstream/import_map.json
- jetstream/package.json
- kv/deno.json
- kv/import_map.json
- kv/package.json
- migration.md
- obj/deno.json
- obj/import_map.json
- obj/package.json
- services/deno.json
- services/import_map.json
- services/package.json
- transport-deno/deno.json
- transport-deno/src/version.ts
- transport-node/package.json
- transport-node/src/version.ts
- transport-node/tests/reconnect_test.js
Introduce a `cleanup` method for socket event handling, ensuring consistent resource cleanup across close/error scenarios. Additionally, implement a test case to verify websocket reconnect functionality after disconnection.
fixes #210
> fix(node): websocket under node doesn't emit close+error (only error) so redials didn't happen

- .github/workflows/consistency_checks.yml
- .github/workflows/core.yml
- .github/workflows/deno_checks.yml
- .github/workflows/jetstream.yml
- .github/workflows/kv.yml
- .github/workflows/node_checks.yml
- .github/workflows/obj.yml
- .github/workflows/services.yml
- .github/workflows/transport-node-test.yml
- .github/workflows/version_bump.yml
The default GitHub ubuntu-latest runners already have 4-cores, so using this hosted runner incurs a cost that isn't necessary. 
Please direct any questions to myself, @krook and @RobertKielty
> Use github-hosted free runners

- jetstream/src/jsapi_types.ts
- jetstream/src/jsm_direct.ts
- jetstream/src/types.ts
- jetstream/tests/direct_consumer_test.ts
- jetstream/tests/jsm_direct_test.ts
The direct APIs are internally used by some operations (KV), but can be very useful to read messages from a stream without having a consumer and by directly interacting with stream replicas. This API can be very useful for some types of applications. This API is non-stable, which means that the API is subject to change.
Refactor direct batch option handling and enforce stricter typing.
Revised typings for `DirectBatchOptions`, ensuring stricter type enforcement and improved clarity between sequence and start time options. Updated corresponding tests and refactored code to align with new type definitions. Added documentation for DirectStreamAPI with notes on non-stable status and potential replica-based inconsistencies.
> feat(js): expose direct APIs

- .github/workflows/npm.yml
Split the NPM publish step into individual workspace-specific tasks for better error handling and maintainability. Each workspace is now published separately with `continue-on-error` enabled to ensure independent failures do not block the workflow.
> Refactor npm publish workflow for granular workspaces

- .github/workflows/npm.yml
Added a manual workflow trigger with `workflow_dispatch` to allow on-demand executions. Updated npm publish steps to include explicit directory navigation and introduced a build step for creating bundles before publishing. These changes improve flexibility and build consistency.
> Add workflow_dispatch trigger and refine npm publish steps

- jetstream/src/jsclient.ts
Updated the conditional statement to ensure proper grouping and evaluate the timeout and no-responders error check accurately. This fixes a potential issue where retries may not trigger as intended.
Fix #247
> fix(jetstream): conditional logic for retry mechanism could bypass rejection of js publish

- jetstream/deno.json
- jetstream/package.json
- jetstream/src/internal_mod.ts
- jetstream/src/jsmstream_api.ts
- jetstream/src/pushconsumer.ts
- jetstream/tests/pushconsumers_ordered_test.ts
- kv/deno.json
- kv/import_map.json
- kv/package.json
- obj/deno.json
- obj/import_map.json
- obj/package.json
- obj/src/objectstore.ts
- transport-node/package.json
- made obj put publish messages sequentially - as current server can drop requests when the producer is too fast. This will degrade put performance.
- changed the internal push consumer used on get, to have an idle_heartbeat, if this fires, the get has stalled, and the ordered consumer should reset.
- enabled flow control on the ordered consumer, this prevents slow consumers when the client is getting very large objects
> Additional hardening of the object store client

- core/src/core.ts
- core/src/nats.ts
- core/tests/basics_test.ts
- core/tests/mrequest_test.ts
Introduce `TraceOptions` in `PublishOptions` to enable message tracing with NATS. Messages can now be traced using `traceDestination` and optionally flagged as `traceOnly` to avoid delivery and generate trace data only. Updated `publish` implementation and added corresponding tests.
> feat(core): tracing

- jetstream/src/jsapi_types.ts
- jetstream/src/jsmconsumer_api.ts
- jetstream/src/types.ts
- jetstream/tests/jsm_test.ts
Introduced a `pedantic` option in `ConsumerApiOptions` to ensure stricter validation of consumer configuration during creation. Updated the `add` method in `jsmconsumer_api.ts` to handle this option, and added a test case to validate pedantic behavior. This enhances flexibility while enforcing stricter checks when needed.
Note the original API allowed for an optional action (a string), now it also allows a ConsumerApiOptions object that allows setting the action and whether it should be pedantic.
> feat(jetstream): support for pedantic mode in consumer creation

- transport-node/package.json
- transport-node/src/connect.ts
- transport-node/src/mod.ts
- transport-node/src/node_transport.ts
- transport-node/src/version.ts
- transport-node/tests/tls_test.js
Introduced `NodeTlsOptions` and `NodeConnectionOptions` types to handle Node.js-specific TLS configuration `rejectUnauthorized`. Updated  transport-node's `connect()` function and related logic to use the new type, and added a relevant test case for TLS behavior.
> Add support for Node-specific TLS options

- jetstream/README.md
This PR updates the full example URLs in JetStream's README. Currently they're linked to `.ts` files which don't exist so I changed them to the JS implementations for now.
> Update URL paths for full JetStream examples

- kv/src/kv.ts
- kv/tests/kv_test.ts
This update introduces a test to ensure JetStream API calls are skipped when using bind-only mode. Additionally, the `jetstreamManager` method now respects the `checkAPI` flag to optimize operations by reducing unnecessary API interactions.
> Add test and logic to bypass JetStream checks for bind-only

- kv/src/kv.ts
- kv/src/types.ts
- kv/tests/kv_test.ts
Introduced optional timeout parameter for `put` and `update` methods, allowing more flexible handling of operation timeouts. Updated relevant tests to verify timeout behavior, including default and custom values. Enhanced type definitions to document the new timeout functionality.
> feat(kv): timeout support for put and update operations

- runtimes.md
> fix(doc): runtime was describing `Svc` (the original name of the type)  instead of `Svcm`

- jetstream/src/jsapi_types.ts
- jetstream/src/jsclient.ts
- jetstream/src/types.ts
- jetstream/tests/jsm_test.ts
- kv/src/kv.ts
- kv/src/types.ts
- kv/tests/kv_test.ts
Introduced `markerTTL` and per-message TTL options, allowing fine-grained control over retention policies. Updated KV methods, types, and tests to support these features, ensuring compatibility with streams enabling `allow_msg_ttl`.
> feat(kv,jetstream)Add support for per-message TTLs in KV and JetStream

- jetstream/src/consumer.ts
- jetstream/src/jserrors.ts
- jetstream/src/types.ts
- jetstream/tests/consume_test.ts
- jetstream/tests/consumers_test.ts
- jetstream/tests/jetstream409_test.ts
- jetstream/tests/next_test.ts
Errors where limits are exceeded (max expires, max waiting, max request batch, message size) - of these only max waiting and message size could auto-heal.
> fix(js): improve handling of 409 status and max_bytes edge cases

- jetstream/src/jsapi_types.ts
- jetstream/tests/jsm_direct_test.ts
Removed unnecessary type assertions from `DirectBatchOptions` in tests. Updated `DirectBatchStartSeq` and `DirectBatchStartTime` types to allow optional mutually exclusive properties for improved type clarity.
[#Fix 285](https://github.com/nats-io/nats.js/issues/285)
> fix(js): better DirectBatchOptions

- jetstream/src/jsapi_types.ts
- jetstream/src/jsclient.ts
- jetstream/src/types.ts
- jetstream/tests/jetstream_test.ts
Introduced the `lastSubjectSequenceSubject` option to enable subject-specific sequence constraints when publishing messages. Updated relevant headers, types, and tests to support this feature.
See https://github.com/nats-io/nats-server/issues/5280
> feat(js): add support for subject-based sequence constraints

- bin/version_manager.ts
- bin/version_manager_test.ts
Small tool to manage versions across all modules in the NATS.js monorepo, handling both Node.js (package.json) and Deno (deno.json) modules.
Commands:
- `check` - Verify version consistency across all modules and their dependencies
- `fix` - Automatically fix version inconsistencies to match expected versions
- `bump <module_name> <version_type>  [--preid <identifier>]` - Bump version of a specific module
- Version types: `major`, `minor`, `patch`, `premajor`, `preminor`, `prepatch`, `prerelease`, `release`
- --preid: Optional identifier for prerelease versions (e.g., alpha, beta, rc)
- `release`: Special type that removes prerelease suffix (e.g., 3.0.3-1 → 3.0.3)
`ls [module_name] [--all]` (alias `list`) - List versions from NPM/JSR registries
- --all: Show all available versions (up to …
> chore: add utility for managing module versions

- jetstream/src/jsm_direct.ts
- jetstream/tests/direct_consumer_test.ts
- jetstream/tests/jsm_test.ts
2.12 corrects pending messages reported by the direct api - this is an internal change that is not visible to client code.
> jsm-direct-pending

- jetstream/src/internal_mod.ts
- jetstream/src/jsapi_types.ts
- jetstream/src/jsclient.ts
- jetstream/src/mod.ts
- jetstream/src/types.ts
- jetstream/tests/schedules_test.ts
feat(jsapi): add support for message scheduling
- Introduced `allow_msg_schedules` in stream configurations to enable scheduling messages.
- Added `ScheduleOptions` type to define scheduling parameters (e.g., specification, target, source, ttl).
- Updated headers to include scheduling fields (`Nats-Schedule`, `Nats-Schedule-Target`, etc.).
- Added tests to validate message scheduling functionality.
> feat(jsapi): add support for message scheduling

- jetstream/src/consumer.ts
- jetstream/src/jsapi_types.ts
- jetstream/src/jsmconsumer_api.ts
- jetstream/src/types.ts
- jetstream/tests/jetstream_pullconsumer_test.ts
- jetstream/tests/jsm_test.ts
- Introduced `PrioritizedOptions` type to define priority options for pull consumers.
- Updated `PullOptions`, `ConsumeOptions`, and related types to include `PrioritizedOptions`.
- Added support for `prioritized` policy to `PriorityPolicy`.
- Implemented validation for priority group settings and pull options.
- Enhanced tests to verify functionality with prioritized groups.
> feat(jsapi): add `PrioritizedOptions` and support for prioritized pull consumers

- jetstream/src/internal_mod.ts
- jetstream/src/jsclient.ts
- jetstream/src/mod.ts
- jetstream/src/types.ts
- Introduced `StreamExpectations` for better assertion handling in message publishing.
- Updated `JetStreamPublishOptions` to utilize `StreamExpectations`.
- Refactored `BatchMessageOptions` and `BatchMessageOptionsWithReply` with `Partial` types for improved flexibility.
- Adjusted `add` method in batch publishing to accept refined option types.
> feat(jetstream): refactor types and enhance batch publishing options

- core/src/internal_mod.ts
- core/src/mod.ts
- core/src/ws_transport.ts
WsConnectionOptions is a `ConnectionOptions` that exposes `wsFactory?: WsSocketFactory`
This enables uses where the runtime is known to provide additional non-standard options that may be necessary for the connection but differ from standard W3C `new WebSocket(url)` usages.
This feature was implemented previously but internal.
> feat: expose in public api ability to create a ws connection by specifying a WsSocketFactory, and referencing it in WsConnectionOptions.

- core/tests/basics_test.ts
- jetstream/src/jsmstream_api.ts
- jetstream/src/types.ts
fix(jestream): fixed the `Stream#deleteMessage()` api to default erase to `true`, as the underlying optional erase from the `JetStreamManager#deleteMessage()` erase's is by default is `true`.
- added additional docs on the Stream apis.
> fix(jestream): fixed the Stream#deleteMessage() api to default erase

- jetstream/src/jserrors.ts
- jetstream/src/jsm_direct.ts
- jetstream/tests/jsm_direct_test.ts
Previously, an error was thrown, but this is inconsistent on how the client handles this conditions for fetch and other similar user-initiated operations.
- Added `isNoResults` method to identify "no results" error in JetStream errors.
- Updated logic in `jsm_direct.ts` to stop iterators on "no results" status.
- Enhanced tests with scenarios for handling batches and direct message retrieval when no messages are available.
Fix #335
> feat(jetstream): handle "no results" status in direct APIs

- core/src/core.ts
- core/src/nats.ts
- core/src/servers.ts
- core/tests/reconnect_test.ts
> feat(core): revert reconnect logic for specifying servers
