jetstream/src/consumer.ts, jetstream/tests/consumers_ordered_test.ts
fix(jetstream): ordered pull consumer would never fail to reset on initial creation if there was an error
https://github.com/nats-io/nats.deno/issues/725
=> ported fix for 725

jetstream/src/consumer.ts, jetstream/src/jsapi_types.ts, jetstream/src/jsmstream_api.ts, jetstream/src/pushconsumer.ts, jetstream/src/types.ts, jetstream/tests/jetstream_pushconsumer_test.ts, jetstream/tests/pushconsumers_ordered_test.ts, kv/src/kv.ts, kv/tests/kv_test.ts, obj/src/objectstore.ts
fixed new push consumer to use inboxPrefix from options if specified
fixed new push consumer subscription leaks
kv - replaced legacy history with one that uses the new push consumer
=> new push consumer fixes and migration

transport-deno/src/deno_transport.ts
fix(transport-deno): fixed possible resource leak if the transport was discarded before it resolved a connection or connection upgrade
=> fixed possible resource leak in the deno transport

transport-node/src/node_transport.ts
fix(transport-node): fixed a possible leak in the node transport in cases where the connect could have been aborted
=> Added additional checks to node transport to prevent possible leaks if transport cancelled connect

migration.md
=> docs(*) - updated migration notes

docs/.nojekyll
=> removed nojekyll

jetstream/examples/01_consumers.ts, jetstream/examples/02_next.ts, jetstream/examples/03_batch.ts, jetstream/examples/04_consume.ts, jetstream/examples/05_consume.ts, jetstream/examples/06_heartbeats.ts, jetstream/examples/07_consume_jobs.ts, jetstream/examples/08_consume_process.ts, jetstream/examples/js_readme_publish_examples.ts, jetstream/examples/jsm_readme_jsm_example.ts, jetstream/examples/util.ts
=> fix(examples): removed module versions

core/src/internal_mod.ts, core/src/mod.ts, core/src/options.ts, core/tests/properties_test.ts, transport-deno/src/connect.ts, transport-deno/tests/basics_test.ts, transport-node/src/connect.ts, transport-node/tests/basics_test.js
=> feat(core,node,deno): added a check on the connect function that the client wasn't given a ws/s:// url as these are difficult issues to diagnose

core/deno.json, core/package.json, core/src/version.ts, jetstream/deno.json, jetstream/import_map.json, jetstream/package.json, kv/deno.json, kv/import_map.json, kv/package.json, obj/deno.json, obj/import_map.json, obj/package.json, services/deno.json, services/import_map.json, services/package.json, transport-deno/deno.json, transport-deno/src/version.ts, transport-node/package.json, transport-node/src/version.ts, transport-node/tests/noiptls_test.js, transport-node/tests/reconnect_test.js
bump(*): all libs
test(node): fix event driven tests
=> fix node test references to removed Events

jetstream/src/jsapi_types.ts, jetstream/src/jsm_direct.ts, jetstream/tests/jsm_direct_test.ts
alllow callbacks for handling direct batch gets
=> internal(direct): handle with optional callback

core/deno.json, core/package.json, core/src/internal_mod.ts, core/src/util.ts, core/src/version.ts, jetstream/deno.json, jetstream/import_map.json, jetstream/package.json, jetstream/src/jsapi_types.ts, jetstream/src/jsbaseclient_api.ts, jetstream/src/jsmsg.ts, jetstream/src/jsmstream_api.ts, jetstream/src/types.ts, jetstream/tests/jsm_test.ts, kv/deno.json, kv/import_map.json, kv/package.json, obj/deno.json, obj/import_map.json, obj/package.json, services/deno.json, services/import_map.json, services/package.json, transport-deno/deno.json, transport-deno/src/version.ts, transport-node/package-lock.json, transport-node/package.json, transport-node/src/version.ts
feat(jetstream): changed "interfaces" into "types"
change(jetstream): JetStreamManager.streams.add() changed its type to be a Partial<StreamConfig> with a required name property. This provides a better ux on completions.
=> jetstream change interfaces into types

README.md
=> Add JSDoc badge

core/README.md, jetstream/README.md, kv/README.md, obj/README.md, services/README.md
=> Add more jsdoc badges: one for each lib

core/README.md, jetstream/README.md, kv/README.md, obj/README.md, services/README.md, transport-deno/README.md, transport-node/README.md
=> doc(*): badges for npm/jsr (jsr not active until actual release)

jetstream/README.md
=> fix broken jetstream link

README.md
=> Add extra link to migration.md

core/src/queued_iterator.ts, core/tests/basics_test.ts, jetstream/tests/consume_test.ts
the pending count included functions (pushed into the iterator, and the current message)
=> more consistent pending count for jetstream iterators

.github/workflows/consistency_checks.yml, .github/workflows/core.yml, .github/workflows/deno_checks.yml, .github/workflows/jetstream.yml, .github/workflows/kv.yml, .github/workflows/node_checks.yml, .github/workflows/obj.yml, .github/workflows/services.yml, .github/workflows/transport-node-test.yml, core/package.json, core/src/denobuffer.ts, jetstream/package.json, jetstream/src/jsmsg.ts, kv/package.json, obj/package.json, services/package.json, transport-node/package.json
Updated the constructor in `denobuffer.ts` to accept both `Uint8Array` and `ArrayBuffer` for TS compatibilty in 5.8 and Deno 2.2x
=> fix(all): TS 5.8 and Deno 2.2 changes to Uint8Array<ArrayBuffer> 

jetstream/src/jsmsg.ts
Added getter for timestampNanos that returns a bigint
fix #214
=> feat(jetstream): JsMsg.timestampNanos as bigint

migration.md
=> update migration doc

jetstream/src/consumer.ts, jetstream/src/jsclient.ts, jetstream/src/jsm_direct.ts, jetstream/src/pushconsumer.ts, migration.md, transport-deno/examples/bench.js
Added shallow copying of options in multiple methods across JetStream modules to prevent unintended mutations. Updated dependencies in the transport-deno example and adjusted formatting in the migration documentation for consistency.
=> Refactor options handling to ensure immutability

jetstream/src/types.ts, jetstream/tests/jetstream_test.ts
=> [FEAT] [JS] expose `retries` on js publish

.github/workflows/npm.yml
=> ci for publishing bundles

.github/workflows/npm.yml
=> fix deno version for bundle publishing

README.md, core/dependencies.md, dependencies.md, jetstream/dependencies.md, kv/dependencies.md, obj/deno.json, obj/dependencies.md, obj/package.json, services/dependencies.md, transport-deno/dependencies.md, transport-deno/examples/bench.js, transport-deno/examples/nats-events.ts, transport-deno/examples/nats-pub.ts, transport-deno/examples/nats-rep.ts, transport-deno/examples/nats-req.ts, transport-deno/examples/nats-sub.ts, transport-node/dependencies.md
Updated the version of @nats-io/obj from 3.0.0 to 3.0.1
=> Bump @nats-io/obj version to 3.0.1

transport-node/tests/tls_test.js
Refactor TLS test assertion for error message validation for dealing with a change in node's error message
=> test: fix message that changed in node 23.11

core/deno.json, core/package.json, core/src/core.ts, core/src/internal_mod.ts, core/src/nats.ts, core/src/version.ts, core/tests/basics_test.ts, jetstream/deno.json, jetstream/import_map.json, jetstream/package.json, jetstream/src/consumer.ts, jetstream/tests/consume_test.ts, kv/deno.json, kv/import_map.json, kv/package.json, obj/deno.json, obj/import_map.json, obj/package.json, services/deno.json, services/import_map.json, services/package.json, services/src/service.ts, services/tests/service_test.ts, transport-deno/deno.json, transport-deno/src/version.ts, transport-node/package.json, transport-node/src/version.ts
Introduced `ConnectionClosedListener` and related methods for improved resource management on connection closes.
Fix #253
=> Add connection close listeners and update package versions

bin/lib/bundle_versions.ts, core/deno.json, core/package.json, core/src/version.ts, jetstream/deno.json, jetstream/import_map.json, jetstream/package.json, kv/deno.json, kv/import_map.json, kv/package.json, obj/deno.json, obj/import_map.json, obj/package.json, services/deno.json, services/import_map.json, services/package.json, transport-deno/deno.json, transport-deno/src/version.ts, transport-node/package.json, transport-node/src/version.ts
Updated package versions, dependencies, and import mappings across multiple modules to ensure consistency with version 3.0.2. Improved repository URL formatting in package metadata.
Corrected a logic error in bundle_versions.ts test script for qualifier comparison.
[ci skip]
=> Bump bundle versions

core/src/protocol.ts, core/tests/basics_test.ts, jetstream/src/consumer.ts, jetstream/src/pushconsumer.ts
Signed-off-by: Alberto Ricart <alberto@synadia.com>
=> refactor(core): remove redundant type assertions in Subscription

core/README.md, jetstream/README.md, kv/README.md, obj/README.md, services/README.md, transport-deno/README.md
=> chore: update README badges that broke when workflows changed

jetstream/src/internal_mod.ts, jetstream/src/jsapi_types.ts, jetstream/src/jserrors.ts
- export JetStreamStatus for consumption downstream
=> feat(jsapi): add `allow_msg_counter` to stream configurations.

jetstream/deno.json, jetstream/package.json, jetstream/src/internal_mod.ts, jetstream/src/jsutil.ts, kv/deno.json, kv/package.json, obj/deno.json, obj/package.json, transport-node/package.json
some internal types exposed to allow support for counters.
=> chore: expose some internal types downstream

runtimes.md
=> docs: add TypeScript compiler configuration guide for Node
